export interface Bug{
    id?: number | string,
    project_name: string,
    category_name: string,
    status_name: string,
    priority_name:string,
    title:string,
    description:string,
    assignee_name:string,
    reporter_name:string,
    created_at?: string,
    update_at?: string,
}
export interface Bug{
    id?: number | string,
    project_name: string,
    category_name: string,
    status_name: string,
    priority_name:string,
    title:string,
    description:string,
    assignee_name:string,
    reporter_name:string,
    created_at?: string,
    update_at?: string,
}